CREATE DATABASE TestDb;
GO

USE TestDb;
GO

CREATE TABLE Product (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),

    CONSTRAINT UC_Product_Name UNIQUE (Name)
);

CREATE NONCLUSTERED INDEX IX_Product_Name ON Product(Name) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON);
GO

CREATE TABLE ProductVersion (
    ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    ProductID UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),
    CreatingDate DATETIME NOT NULL DEFAULT GETDATE(),
    Width FLOAT NOT NULL,
    Height FLOAT NOT NULL,
    Length FLOAT NOT NULL,
    CONSTRAINT FK_ProductVersion_Product FOREIGN KEY (ProductID) REFERENCES Product(ID) ON DELETE CASCADE
);

CREATE NONCLUSTERED INDEX IX_ProductVersion_Name ON ProductVersion(Name) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON);
CREATE NONCLUSTERED INDEX IX_ProductVersion_CreatingDate ON ProductVersion(CreatingDate) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON);
CREATE NONCLUSTERED INDEX IX_ProductVersion_Width ON ProductVersion(Width) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON);
CREATE NONCLUSTERED INDEX IX_ProductVersion_Height ON ProductVersion(Height) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON);
CREATE NONCLUSTERED INDEX IX_ProductVersion_Length ON ProductVersion(Length) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON);
GO

CREATE TABLE EventLog (
    ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    EventDate DATETIME NOT NULL DEFAULT GETDATE(),
    Description NVARCHAR(MAX),
);

CREATE NONCLUSTERED INDEX IX_EventLog_EventDate ON EventLog(EventDate) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON);
GO
